
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 09 16:31:20 CDT 2024
//----------------------------------------------------

package skelprototype;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Residuo = 25;
  public static final int Entero = 2;
  public static final int Coma = 7;
  public static final int If = 18;
  public static final int Relacional = 15;
  public static final int Clase = 5;
  public static final int Else = 19;
  public static final int MetodoRetorno = 36;
  public static final int Arroba = 24;
  public static final int LlaveCierre = 14;
  public static final int NOT = 28;
  public static final int AND = 32;
  public static final int Asigna = 22;
  public static final int Booleano = 9;
  public static final int OR = 31;
  public static final int ParentesisCierre = 12;
  public static final int Punto = 34;
  public static final int Division = 30;
  public static final int NumeroDecimal = 21;
  public static final int Cadena = 10;
  public static final int EOF = 0;
  public static final int LlaveApertura = 13;
  public static final int error = 1;
  public static final int Import = 4;
  public static final int Texto = 23;
  public static final int MetodoVacio = 35;
  public static final int ERROR = 38;
  public static final int TrueFalse = 16;
  public static final int FinDeLinea = 17;
  public static final int Identificador = 6;
  public static final int Resta = 29;
  public static final int Caracter = 27;
  public static final int Retorno = 37;
  public static final int Multiplicacion = 26;
  public static final int Decimal = 3;
  public static final int Numero = 20;
  public static final int ParentesisApertura = 11;
  public static final int Suma = 33;
  public static final int Comillas = 8;
}

